# .github/workflows/build.yml
name: Compiler

on: [push]

jobs:
  package:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Run atlas-compile
        run: atlas-package
      - name: Locate target filws
        run: ls -l target

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
