# .github/workflows/build.yml
name: Compiler

on:
  push:
    branches-ignore:
      - main

jobs:
  mainBuild:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}
#      - name: Run atlas-compile
#        run: atlas-package -Dmaven.javadoc.skip=true
      - name: Locate target filws
        run: ls -l target

      - name: Publish to GitHub Packages
        run: mvn --batch-mode -Dmaven.javadoc.skip=true -DuseGitHubPackages=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
