# .github/workflows/build.yml
name: Node Build.

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Run atlas-compile
        run: ls -la
