# .github/workflows/build.yml
name: Release

on:
  push:
    branches:
      - main

jobs:
  mailBuild:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Run atlas-release
        run: atlas-release